// THIS FILE IS AUTOGENERATED; DO NOT EDIT

package cmd

func init() {
	rootCmd.AddCommand(
		days.NewFourCommand(),
		days.NewOneCommand(),
		days.NewThreeCommand(),
		days.NewTwoCommand(),
		days.NewFiveCommand(),
	)
}
